language: nix
sudo: false

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack
    - .stack-work

matrix:
  fast_finish: true
  include:
    - env: GHCVER=8.4.3 CACHE_NAME=8.4.3 BUILD_BINARY=1
      compiler: ": #stack 8.4.3"
      addons: {apt: {packages: [ghc-8.4.3], sources: [hvr-ghc]}}

install:
 - unset CC
 - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
 - mkdir -p ~/.local/bin
 - curl -sL https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
 - travis_retry stack --no-terminal setup

script:
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - GHC_OPTIONS="-Werror"
 - |
   set -ex
   stack --no-terminal test --ghc-options="$GHC_OPTIONS"
   set +ex