name:                haskell-bas
version:             0.1.0.0
github:              "githubuser/haskell-bas"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/haskell-bas#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- bytestring
- filepath
- fsnotify
- vty
- haskeline
- microlens
- microlens-th
- mtl
- options
- text
- ansi-wl-pprint
- yaml
- sqlite-simple
library:
  source-dirs: src

executables:
  haskell-bas:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-bas

tests:
  haskell-bas-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-bas
